version: '3.7'

services:
  php:
    depends_on:
      - mysql
    build:
      context: ./docker
      target: php
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: 'dev'
      COMPOSER_PROCESS_TIMEOUT: 1800
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/var:/srv/api/var:rw
    expose:
      - 9000

  api:
    build:
      context: ./docker
      target: web
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    depends_on:
      - php
    environment:
      DEPLOY_URL: $DEPLOY_URL
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./api/public:/srv/api/public:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${API_PORT}:80"

  mysql:
    ports:
      - "${MYSQL_PORT}:3306"
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MGMNT_PORT}:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq/mnesia
      - rabbit-logs:/var/log/rabbitmq

  consumer:
    depends_on:
      - mysql
      - rabbitmq
    build:
      context: ./docker
      target: consumer
      dockerfile: dev.Dockerfile
    command: /bin/commands/news.sh
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: 'dev'
      COMPOSER_PROCESS_TIMEOUT: 1800
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/var:/srv/api/var:rw



volumes:
  rabbit-data: ~
  rabbit-logs: ~
  db-data: ~
