parameters:
    env(MYSQL_VERSION): '8.0'
    env(MYSQL_HOST): 'db'
    env(MYSQL_DATABASE): 'db'
    env(MYSQL_PASSWORD): 'db'
    env(MYSQL_USER): 'db'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '%env(MYSQL_VERSION)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        host: '%env(resolve:MYSQL_HOST)%'
        dbname: '%env(resolve:MYSQL_DATABASE)%'
        user: '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_PASSWORD)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
